# Signal detection theory: from an ideal observer to psychometric functions
# Copyright © 2026 Suresh Krishna.
# Licensed as a complete educational work under CC BY-NC-SA 4.0:
# https://creativecommons.org/licenses/by-nc-sa/4.0/
# Attribution details:
# https://github.com/m2b3/QuantBehavior/blob/main/LICENSE-CONTENT.md
#
# Standalone R companion to sdt.py. Run with:
#   Rscript sdt.R
# or source it from RStudio. It uses only base R (including the recommended
# stats and graphics packages), so no package installation is required.
#
# Contents
#   1. The ideal equal-variance model
#   2. What changes in real observers?
#   3. Simulated yes/no data
#   4. Fit a psychometric function
#   5. From SDT to stimulus-dependent psychometric functions
#   Appendix: selected extensions

options(stringsAsFactors = FALSE)

# Small helpers used throughout. Sorting inside auc_trapezoid makes it work
# whether an ROC was generated by increasing or decreasing thresholds.
auc_trapezoid <- function(x, y) {
  keep <- is.finite(x) & is.finite(y)
  x <- x[keep]
  y <- y[keep]
  ordering <- order(x)
  x <- x[ordering]
  y <- y[ordering]
  sum(diff(x) * (head(y, -1) + tail(y, -1)) / 2)
}

find_curve_crossing <- function(grid, difference, target = mean(range(grid))) {
  crossing_indices <- which(diff(sign(difference)) != 0)
  if (length(crossing_indices) == 0) {
    stop("No curve crossing was found on the supplied grid.")
  }
  crossings <- vapply(crossing_indices, function(index) {
    x1 <- grid[index]
    x2 <- grid[index + 1]
    y1 <- difference[index]
    y2 <- difference[index + 1]
    x1 - y1 * (x2 - x1) / (y2 - y1)
  }, numeric(1))
  crossings[which.min(abs(crossings - target))]
}

simulate_yes_count <- function(mean_response, n_trials, criterion, lapse) {
  internal_response <- rnorm(n_trials, mean_response, 1)
  respond_yes <- internal_response > criterion
  lapse_trials <- runif(n_trials) < lapse
  respond_yes[lapse_trials] <- runif(sum(lapse_trials)) < 0.5
  sum(respond_yes)
}

# -----------------------------------------------------------------------------
# 1. The ideal equal-variance model
# -----------------------------------------------------------------------------
# Imagine equally common signal and noise trials. Each trial creates a noisy,
# one-dimensional internal response. Signal responses tend to be larger, but
# the distributions overlap. Examples include baggage screening, radiology,
# hearing one's name, or diagnosing a sample from a noisy test.
#
# Our deliberately idealized starting assumptions are Gaussian signal and
# noise distributions with equal variance, independent stationary trials, one
# fixed decision criterion, and no stimulus-independent guesses or lapses.
#
# Three tasks that are easy to confuse
# Task                         Trial and response                 Direct summary
# Yes/no detection             Signal present/absent; say yes/no Hits, false alarms,
#                                                                d' and criterion
# Single-interval 2AFC         Category A or B; say A or B       A two-by-two table
# (identification)                                               after naming one
#                                                                category "positive"
# 2I-2AFC detection            Signal in interval 1 or 2;        Proportion correct
#                              choose its interval                and d'
#
# "2AFC" is sometimes used as shorthand for the two-interval task. Saying
# 1I-2AFC or 2I-2AFC removes that ambiguity. Sensitivity, specificity, recall,
# precision, and PPV apply naturally to yes/no detection and single-interval
# classification. In ordinary 2I-2AFC, a signal occurs somewhere on every
# trial, so catch trials or a separate yes/no task are needed to estimate
# detection specificity and predictive value.

x <- seq(0, 100, length.out = 1000)
diff_x <- seq(-100, 100, length.out = 1000)
loc_noise <- 40
sd_noise <- 10
loc_signal <- 60
sd_signal <- 10
pdf_noise <- dnorm(x, loc_noise, sd_noise)
pdf_signal <- dnorm(x, loc_signal, sd_signal)
criterion <- (loc_noise + loc_signal) / 2
intersection_point <- find_curve_crossing(
  x, pdf_signal - pdf_noise, (loc_noise + loc_signal) / 2
)

right_of_criterion <- x >= criterion
left_of_criterion <- x < criterion
arrow_height <- 1.08 * max(pdf_noise, pdf_signal)
plot(
  x, pdf_noise, type = "n", ylim = c(0, 1.28 * arrow_height),
  xlab = "Internal evidence", ylab = "Density",
  main = "Figure 1. Equal-variance Gaussian evidence in a yes/no task"
)
polygon(
  c(x[left_of_criterion], rev(x[left_of_criterion])),
  c(pdf_noise[left_of_criterion], rep(0, sum(left_of_criterion))),
  col = adjustcolor("red", alpha.f = 0.07), border = NA
)
polygon(
  c(x[right_of_criterion], rev(x[right_of_criterion])),
  c(pdf_signal[right_of_criterion], rep(0, sum(right_of_criterion))),
  col = adjustcolor("blue", alpha.f = 0.20), border = NA
)
polygon(
  c(x[right_of_criterion], rev(x[right_of_criterion])),
  c(pdf_noise[right_of_criterion], rep(0, sum(right_of_criterion))),
  density = 18, angle = 45, col = adjustcolor("red", alpha.f = 0.65),
  border = NA
)
lines(x, pdf_noise, col = "red", lwd = 2)
lines(x, pdf_signal, col = "blue", lwd = 2)
abline(v = criterion, lty = 2, lwd = 1.5)
points(
  intersection_point,
  dnorm(intersection_point, loc_signal, sd_signal),
  pch = 19
)
arrows(
  loc_noise, arrow_height, loc_signal, arrow_height,
  code = 3, angle = 20, length = 0.08, col = "purple4", lwd = 2
)
text(
  loc_noise + 0.25 * (loc_signal - loc_noise),
  1.02 * arrow_height, "d'", col = "purple4", font = 2, cex = 1.25,
  pos = 3, offset = 0.15
)
legend(
  "topleft",
  c(
    sprintf("Noise trials: mean=%g, SD=%g", loc_noise, sd_noise),
    sprintf("Signal trials: mean=%g, SD=%g", loc_signal, sd_signal),
    sprintf("Decision criterion k=%g (c=0)", criterion),
    "H: hit area", "F: false-alarm area"
  ),
  col = c("red", "blue", "black", "blue", "red"),
  lty = c(1, 1, 2, NA, NA), lwd = c(2, 2, 1.5, NA, NA),
  pch = c(NA, NA, NA, 15, 15), pt.cex = c(NA, NA, NA, 1.4, 1.4),
  bty = "n", cex = 0.72, ncol = 2
)
grid()

# How to read Figure 1: the black dashed line is the decision threshold;
# evidence to its right produces a "signal" response. The purple arrow marks
# d', the peak-to-peak distance measured with the common SD as the ruler. The
# curves drawn here happen to give d'=2 because their peaks are 20 units apart
# and their SD is 10. That is an illustrative choice, not a fixed value of d'.
# Criterion c tells us where the black line lies relative to the midpoint.
# The blue area right of the line is the hit rate H; the hatched red area right
# of it is the false-alarm rate F; the pale red area left of it is specificity.
#
# Figures 2A and 2B move this decision line through every possible position.
# Very low thresholds create many hits and false alarms; very high thresholds
# create few of both. This movable decision threshold differs from a fixed
# sensory threshold; Appendix A3 summarizes the classic ROC evidence.
# In multidimensional or non-Gaussian problems, the optimal acceptance region
# can be more complicated than one threshold.
thresholds <- seq(min(x), max(x), length.out = 1000)
tpr_theoretical <- 1 - pnorm(thresholds, loc_signal, sd_signal)
fpr_theoretical <- 1 - pnorm(thresholds, loc_noise, sd_noise)
p_correct_theoretical <- 0.5 * (tpr_theoretical + 1 - fpr_theoretical)

roc_fpr_theoretical <- c(1, fpr_theoretical, 0)
roc_tpr_theoretical <- c(1, tpr_theoretical, 0)
roc_auc <- auc_trapezoid(roc_fpr_theoretical, roc_tpr_theoretical)
cat(sprintf("Area under the theoretical ROC curve: %.4f\n", roc_auc))

# Internal checks use analytic identities that do not depend on a random seed.
dprime_theoretical <- (loc_signal - loc_noise) / sd_noise
auc_analytic <- pnorm(dprime_theoretical / sqrt(2))
stopifnot(
  abs(sd_signal - sd_noise) < .Machine$double.eps^0.5,
  abs(intersection_point - (loc_noise + loc_signal) / 2) < 2 * diff(x)[1],
  abs(roc_auc - auc_analytic) < 5e-4,
  abs(max(p_correct_theoretical) - pnorm(dprime_theoretical / 2)) < 5e-4
)

set.seed(602)
n_trials <- 10000
n_half <- n_trials %/% 2
samples_noise <- rnorm(n_half, loc_noise, sd_noise)
samples_signal <- rnorm(n_half, loc_signal, sd_signal)
samples <- c(samples_noise, samples_signal)
labels <- c(rep(FALSE, n_half), rep(TRUE, n_half))

tpr_simulation <- numeric(length(thresholds))
fpr_simulation <- numeric(length(thresholds))
for (i in seq_along(thresholds)) {
  predictions <- samples > thresholds[i]
  tpr_simulation[i] <- mean(predictions[labels])
  fpr_simulation[i] <- mean(predictions[!labels])
}

old_par <- par(mfrow = c(1, 2))
plot(
  thresholds, p_correct_theoretical, type = "l", lwd = 2,
  xlab = "Threshold", ylab = "Chance of a correct response",
  main = "Figure 2A. Accuracy as the decision threshold moves"
)
abline(v = intersection_point, lty = 2)
grid()

plot(
  roc_fpr_theoretical, roc_tpr_theoretical, type = "l", lwd = 2,
  xlim = c(0, 1), ylim = c(0, 1),
  xlab = "False-alarm rate (the opposite of specificity)",
  ylab = "Hit rate (sensitivity / recall)",
  main = "Figure 2B. The same thresholds traced in ROC space"
)
lines(c(1, fpr_simulation, 0), c(1, tpr_simulation, 0), lty = 2, lwd = 2)
abline(0, 1, col = "navy", lty = 3)
legend(
  "bottomright", c("Theoretical", "Simulation", "Chance"),
  lty = c(1, 2, 3), lwd = 2, col = c("black", "black", "navy"), bty = "n"
)
grid()
par(old_par)

# Standard SDT measures
# P(X > k | signal) means the chance that signal-trial evidence lands to the
# right of the decision line: the blue area in Figure 1. Call this H. Replacing
# signal with noise gives F, the hatched red area to the right of the line.
# Under the equal-variance Gaussian model:
#   d'   = qnorm(H) - qnorm(F) = (mu_signal - mu_noise) / sigma
# In plain language, d' is the purple peak-to-peak distance in Figure 1, using
# the common SD as the ruler. qnorm merely converts an area into that SD ruler.
# Larger d' means less overlap. Moving the criterion does not move the peaks.
#
#   c    = -0.5 * (qnorm(H) + qnorm(F))
# In plain language, c locates the black line relative to the midpoint: zero at
# the midpoint, positive when shifted right (conservative), and negative when
# shifted left (liberal), all measured on the same SD ruler.
#
#   beta = f_signal(k) / f_noise(k) = exp(d' * c)
# In plain language, beta compares the heights of the signal and noise curves
# at the black line. At their crossing the heights match, so beta=1. With equal
# priors and costs this crossing maximizes accuracy and c=0. These shortcuts
# assume equal-variance Gaussians; comparing the two sources remains more general.

# -----------------------------------------------------------------------------
# 2. What changes in real observers?
# -----------------------------------------------------------------------------
# The ideal model is a baseline, not a literal description of every observer.
#
# Ideal assumption             Plausible departure / consequence
# Equal Gaussian variance      Unequal or non-Gaussian evidence changes ROC shape
# One fixed criterion          Drift, sequential bias, or payoff changes add variance
# Fixed sensitivity            Learning, fatigue, attention, and adaptation change d'
# No guesses or lapses         Stimulus-independent responses alter both asymptotes
# One mechanism                Strategy/state mixtures may not form one sigmoid
# Independent binomial trials  Serial dependence causes overdispersion
#
# Add complexity only when the design identifies it. Inspect residuals, recover
# parameters in simulations, compare constrained models, and prefer predictive
# or principled model comparisons over appearance alone. With unequal Gaussian
# variances, use a binormal/zROC analysis. AUC, A', and d_a answer related but
# different questions and do not rescue a poorly identified design.

# -----------------------------------------------------------------------------
# 3. Simulated yes/no data
# -----------------------------------------------------------------------------
# The next formula is a compact recipe for the simulation. On signal trials:
#   X | signal,x ~ Normal(d'(x), 1), with d'(x) = gain * x.
# In plain language, draw an evidence value X from a bell curve centered at
# d'(x) with SD one. Increasing contrast moves its peak right; gain says how
# far per contrast unit. Noise-only catch trials use a curve centered at zero.
# The observer says "signal" when X lands right of k, as in Figure 1. Figure 3
# shows many such trials; lapses occasionally replace this rule with a guess.

set.seed(604)
contrast_levels <- c(0.25, 0.5, 1, 2, 4, 8, 12, 16)
n_per_level <- 160
n_catch <- 240
gain_true <- 0.25
criterion_true <- 1.0
lapse_true <- 0.02
true_dprime <- gain_true * contrast_levels

yes_counts <- vapply(
  true_dprime,
  simulate_yes_count,
  integer(1),
  n_trials = n_per_level,
  criterion = criterion_true,
  lapse = lapse_true
)
false_alarm_count <- simulate_yes_count(
  0, n_catch, criterion_true, lapse_true
)
false_alarm_rate <- false_alarm_count / n_catch

psychometric_data <- data.frame(
  contrast = contrast_levels,
  yes = yes_counts,
  trials = rep(n_per_level, length(contrast_levels))
)

contrast_grid <- seq(0, max(contrast_levels), length.out = 400)
p_yes_generating <- lapse_true / 2 +
  (1 - lapse_true) * pnorm(gain_true * contrast_grid - criterion_true)
plot(
  contrast_grid, p_yes_generating, type = "l", lwd = 2,
  xlab = "Contrast (%)", ylab = "Chance of a 'signal' response",
  ylim = c(0, 1), main = "Figure 3. Simulated yes/no responses across contrast"
)
points(contrast_levels, yes_counts / n_per_level, pch = 19, col = "blue")
points(0, false_alarm_rate, pch = 4, cex = 1.4, lwd = 2, col = "red")
legend(
  "bottomright",
  c("Generating model", "Signal trials", "Noise-only catch trials"),
  col = c("black", "blue", "red"), lty = c(1, NA, NA),
  pch = c(NA, 19, 4), lwd = c(2, NA, 2), bty = "n"
)
grid()

cat(sprintf(
  "Noise-only catch trials: %d of %d produced a 'signal' response.\n",
  false_alarm_count, n_catch
))
cat("Contrast | signal responses / trials\n")
for (i in seq_along(contrast_levels)) {
  cat(sprintf("%8.2f | %3d / %d\n", contrast_levels[i], yes_counts[i], n_per_level))
}

# -----------------------------------------------------------------------------
# 4. Fit a psychometric function
# -----------------------------------------------------------------------------
# R has several possible psychometric-fitting routes. stats::glm is excellent
# for ordinary logit/probit binomial models without fitted lapses. The psyphy
# package (sometimes described informally as "R psychophysics") supplies SDT
# utilities, psychophysical GLM links, and psyfun.2asym; quickpsy adds a convenient
# multi-group/bootstrap workflow; brms can express richer Bayesian models. To
# keep this file immediately runnable, the code below directly maximizes the
# grouped-binomial likelihood with base stats::optim. This also lets us impose
# the same lower/upper-asymptote constraint used in the Python and MATLAB files.
#
# Curve choices:
#   norm     additive Gaussian decision noise: Phi(beta * (x - alpha))
#            In plain language, response chance is accumulated bell-curve area;
#            alpha moves the S-curve and beta controls how quickly it rises.
#   logistic logistic decision noise: plogis(beta * (x - alpha))
#            In plain language, every stimulus step adds a fixed amount to the
#            response log-odds. It resembles a Gaussian with heavier tails.
#   weibull  positive intensities: 1 - exp(-(x / alpha)^beta)
#            In plain language, the chance that every possible detection event
#            fails shrinks with intensity; alpha sets scale and beta sets shape.
#
# The response probability is q + (1 - 2q) * core(x), where the lower and
# upper error asymptotes are constrained to the same q. Under random lapses,
# the corresponding total lapse probability is 2q.

sigmoid_name <- "norm"  # Change to "logistic" or "weibull".

predict_psychometric <- function(theta, stimulus, sigmoid) {
  # q is constrained to (0, 0.1), slope/scale parameters stay positive.
  q <- 0.1 * plogis(theta[3])
  if (sigmoid == "weibull") {
    alpha <- exp(theta[1])
    beta <- exp(theta[2])
    core <- 1 - exp(-(pmax(stimulus, 0) / alpha)^beta)
  } else {
    alpha <- theta[1]
    beta <- exp(theta[2])
    linear_predictor <- beta * (stimulus - alpha)
    core <- if (sigmoid == "norm") pnorm(linear_predictor) else
      plogis(linear_predictor)
  }
  q + (1 - 2 * q) * core
}

psychometric_nll <- function(theta, data, sigmoid) {
  probabilities <- predict_psychometric(theta, data$contrast, sigmoid)
  probabilities <- pmin(pmax(probabilities, 1e-12), 1 - 1e-12)
  -sum(dbinom(data$yes, data$trials, probabilities, log = TRUE))
}

if (sigmoid_name == "weibull") {
  theta_start <- c(log(median(contrast_levels)), log(2), qlogis(0.1))
} else {
  theta_start <- c(median(contrast_levels), log(0.25), qlogis(0.1))
}

psychometric_fit <- optim(
  theta_start,
  psychometric_nll,
  data = psychometric_data,
  sigmoid = sigmoid_name,
  method = "Nelder-Mead",
  control = list(maxit = 10000, reltol = 1e-10),
  hessian = TRUE
)

fit_theta <- psychometric_fit$par
fit_q <- 0.1 * plogis(fit_theta[3])
if (sigmoid_name == "weibull") {
  fit_alpha <- exp(fit_theta[1])
  fit_beta <- exp(fit_theta[2])
} else {
  fit_alpha <- fit_theta[1]
  fit_beta <- exp(fit_theta[2])
}

fit_grid <- seq(0, max(contrast_levels), length.out = 400)
fit_probability <- predict_psychometric(fit_theta, fit_grid, sigmoid_name)
plot(
  fit_grid, fit_probability, type = "l", lwd = 2,
  xlab = "Contrast (%)", ylab = "Proportion of signal responses",
  ylim = c(0, 1), main = sprintf("Figure 4. Psychometric fit (%s link)", sigmoid_name)
)
points(contrast_levels, yes_counts / n_per_level, pch = 19, col = "blue")
grid()

cat(sprintf(
  paste0(
    "Psychometric fit (%s): alpha = %.4f, beta = %.4f, ",
    "equal asymptote q = %.4f (random-lapse probability = %.4f); convergence = %d\n"
  ),
  sigmoid_name, fit_alpha, fit_beta, fit_q, 2 * fit_q,
  psychometric_fit$convergence
))
stopifnot(
  psychometric_fit$convergence == 0,
  is.finite(psychometric_fit$value),
  all(fit_probability > 0 & fit_probability < 1),
  fit_beta > 0,
  fit_q >= 0 && fit_q <= 0.1
)

# -----------------------------------------------------------------------------
# 5. From SDT to stimulus-dependent psychometric functions
# -----------------------------------------------------------------------------
# With unit variance and fixed criterion k:
#   H(x) = Phi(d'(x) - k), and F = Phi(-k).
# In plain language, H(x) is the blue area to the right of Figure 1's decision
# line after contrast moves the blue curve. F is the red area right of the line;
# here it stays fixed because the noise curve and criterion do not move. Phi
# converts a horizontal distance into accumulated area under a bell curve.
#
# Thus the psychometric curve depends jointly on the decision rule and the
# transducer mapping stimulus to d'. If d'(x)=gain*x, each contrast step moves
# the signal peak equally and H(x) is cumulative Gaussian. A common extension:
#   d'(x) = (gain*x)^p.
# In plain language, gain controls overall peak separation and p lets that
# separation grow faster or slower than a straight line. Figure 5 plots it.
#
# Fit signal and noise responses jointly when asking whether a manipulation
# changes gain, exponent, criterion, or lapse rate. If false-alarm rate or
# criterion changes with stimulus or condition, fitting hit rates alone
# confounds sensitivity and bias.

# The log-linear correction avoids infinite z-scores for observed rates 0 or 1.
hit_rate_corrected <- (yes_counts + 0.5) / (n_per_level + 1)
false_alarm_rate_corrected <- (false_alarm_count + 0.5) / (n_catch + 1)
empirical_dprime <- qnorm(hit_rate_corrected) - qnorm(false_alarm_rate_corrected)
stopifnot(
  all(is.finite(empirical_dprime)),
  length(empirical_dprime) == length(contrast_levels)
)

plot(
  contrast_levels, empirical_dprime, pch = 19,
  xlab = "Contrast (%)", ylab = "d'",
  main = "Figure 5. Sensitivity grows with contrast"
)
lines(contrast_levels, true_dprime, lwd = 2)
legend(
  "topleft", c("Estimated d' from hit and false-alarm areas", sprintf("Generating d' = %.2f x", gain_true)),
  pch = c(19, NA), lty = c(NA, 1), lwd = c(NA, 2), bty = "n"
)
grid()

# -----------------------------------------------------------------------------
# Appendix A1. Reading a two-by-two table in plain language
# -----------------------------------------------------------------------------
# Diagnostic example:
# Actual state       Test positive       Test negative       Total
# Disease present    40 hits             10 misses           50
# Disease absent     15 false alarms     135 correct rejects 150
# Total              55                  145                 200
#
# Sensitivity/recall asks: among the 50 people with disease, how many test
# positive? Look across that row: 40 are found and 10 are missed.
# Specificity asks: among the 150 people without disease, how many test
# negative? Look across that row: 135 are cleared and 15 falsely alarm.
# Precision/PPV reverses the question: among the 55 positive tests, how many
# actually have disease? Look down that column: 40 do and 15 do not.
#
# The same arrangement describes stimulus detection:
# Actual stimulus    Say "I see it"      Say "I don't see it" Total
# Present            40 hits             10 misses            50
# Absent             15 false alarms     135 correct rejects  150
# Total              55                  145                  200
#
# It also describes two-category discrimination when clockwise is designated
# the "positive" category:
# Actual tilt        Say "clockwise"     Say "counterclockwise" Total
# Clockwise          40 hits             10 misses               50
# Counterclockwise   15 false alarms     135 correct rejects     150
# Total              55                  145                     200
# Calling counterclockwise "positive" would swap the outcome labels, not the
# observations. The positive category is bookkeeping, not a special stimulus.
#
# Sensitivity/recall and specificity begin with the actual state and look
# across a row. Precision/PPV begins with the response and looks down a column;
# it therefore changes with the signal base rate. In SDT, sensitivity/recall is
# H and one minus specificity is F. Clinical "sensitivity" (H) is not the same
# as the SDT discriminability index d': moving criterion changes H, not d'.
#
# The log-linear correction below is used only for d' and c, preventing an
# observed "never" or "always" response from producing an infinite z-score.

hits <- 40
misses <- 10
false_alarms <- 15
correct_rejections <- 135
hit_rate <- hits / (hits + misses)
false_alarm_rate_example <- false_alarms / (false_alarms + correct_rejections)
specificity <- correct_rejections / (false_alarms + correct_rejections)
precision <- hits / (hits + false_alarms)
hit_rate_corrected_example <- (hits + 0.5) / (hits + misses + 1)
fa_rate_corrected_example <-
  (false_alarms + 0.5) / (false_alarms + correct_rejections + 1)
z_hit <- qnorm(hit_rate_corrected_example)
z_false_alarm <- qnorm(fa_rate_corrected_example)
dprime_observed <- z_hit - z_false_alarm
criterion_observed <- -0.5 * (z_hit + z_false_alarm)
stopifnot(
  is.finite(dprime_observed),
  is.finite(criterion_observed),
  dprime_observed > 0,
  abs(specificity - (1 - false_alarm_rate_example)) < 1e-12,
  precision > 0 && precision < 1
)

cat(sprintf(
  "Sensitivity / recall: among %d people with disease, %d test positive and %d test negative.\n",
  hits + misses, hits, misses
))
cat(sprintf(
  "Specificity: among %d people without disease, %d test negative and %d test positive.\n",
  false_alarms + correct_rejections, correct_rejections, false_alarms
))
cat(sprintf(
  "Precision / PPV: among %d positive tests, %d come from people with disease and %d do not.\n",
  hits + false_alarms, hits, false_alarms
))
cat(sprintf("Corrected d': %.3f; corrected c: %.3f\n", dprime_observed, criterion_observed))

# Appendix A2. Unequal variance and alternative sensitivity indices
# If sigma_signal != sigma_noise, qnorm(H)-qnorm(F) varies with criterion.
# The zROC follows:
#   qnorm(H) = (mu_signal-mu_noise)/sigma_signal
#              + (sigma_noise/sigma_signal) * qnorm(F).
# In plain language, qnorm redraws each ROC axis with an SD ruler, making the
# ROC a line. Its tilt is sigma_noise/sigma_signal; equal widths give one. If
# widths differ, peak-distance d' depends on which spread is used. The log
# likelihood ratio is curved and can cross the cutoff twice, so "signal" need
# not mean every value right of one line. ROC/AUC and the general rule remain
# valid. A', d_a, and equal-variance d' have different interpretations.

# -----------------------------------------------------------------------------
# Appendix A3. Why ROC experiments mattered
# -----------------------------------------------------------------------------
# A single H,F pair cannot reveal ROC shape. Classic experiments held signal
# strength roughly fixed while moving criterion through priors/payoffs, or used
# confidence ratings as several criteria. This separates willingness to say
# "signal" from sensitivity. Continuous-evidence SDT predicts a smooth bowed
# ROC; the simplest high-threshold theory predicts straight-line structure.
# Yes/no and forced-choice detectability agreed, rating ROCs favored graded
# evidence, and above-chance second choices challenged the simplest all-or-none
# account. Luce's low-threshold model and later multi-state threshold models
# show that these results do not prove every internal distribution is Gaussian.
# Rich ROC data are needed for detailed model discrimination.
# Sources: Tanner & Swets (1954), doi:10.1037/h0058700; Swets, Tanner, &
# Birdsall (1961), doi:10.1037/h0040547; Luce (1963), doi:10.1037/h0039723;
# Nachmias & Steinman (1963), doi:10.1364/JOSA.53.001206; Krantz (1969),
# doi:10.1037/h0027238.

# -----------------------------------------------------------------------------
# Appendix A4. Two-interval, two-alternative forced choice
# -----------------------------------------------------------------------------
# Each trial contains one A/signal and one B/noise observation. The observer
# knows A is present and chooses its interval; "signal absent" is not an option.
# Figure 6 plots D = interval-1 observation minus interval-2 observation. Blue
# is A in interval 1, red is A in interval 2, and zero separates the choices.

delta_difference <- loc_signal - loc_noise
sd_difference <- sqrt(sd_noise^2 + sd_signal^2)
pdf_signal_minus_noise <- dnorm(diff_x, delta_difference, sd_difference)
pdf_noise_minus_signal <- dnorm(diff_x, -delta_difference, sd_difference)
right_of_zero <- diff_x >= 0
left_of_zero <- diff_x <= 0
difference_arrow_height <- 1.08 * max(
  pdf_signal_minus_noise, pdf_noise_minus_signal
)
plot(
  diff_x, pdf_signal_minus_noise, type = "n",
  ylim = c(0, 1.28 * difference_arrow_height),
  xlab = "Difference D", ylab = "Density",
  main = "Figure 6. 2I-2AFC decision variable: D = X1 - X2"
)
polygon(
  c(diff_x[right_of_zero], rev(diff_x[right_of_zero])),
  c(pdf_signal_minus_noise[right_of_zero], rep(0, sum(right_of_zero))),
  col = adjustcolor("blue", alpha.f = 0.18), border = NA
)
polygon(
  c(diff_x[left_of_zero], rev(diff_x[left_of_zero])),
  c(pdf_noise_minus_signal[left_of_zero], rep(0, sum(left_of_zero))),
  col = adjustcolor("red", alpha.f = 0.18), border = NA
)
lines(diff_x, pdf_signal_minus_noise, col = "blue", lwd = 2)
lines(diff_x, pdf_noise_minus_signal, col = "red", lwd = 2)
abline(v = 0, lty = 2, lwd = 1.5)
arrows(
  -delta_difference, difference_arrow_height,
  delta_difference, difference_arrow_height,
  code = 3, angle = 20, length = 0.08, col = "purple4", lwd = 2
)
text(
  -delta_difference / 2, 1.02 * difference_arrow_height,
  "2 Delta between conditional means", col = "purple4", font = 2,
  pos = 3, offset = 0.15, cex = 0.85
)
legend(
  "topright",
  c(
    "A in interval 1: mean +Delta", "A in interval 2: mean -Delta",
    "Choose interval 1 if D > 0", "Correct area: A in interval 1",
    "Correct area: A in interval 2"
  ),
  col = c("blue", "red", "black", "blue", "red"),
  lty = c(1, 1, 2, NA, NA), lwd = c(2, 2, 1.5, NA, NA),
  pch = c(NA, NA, NA, 15, 15), bty = "n", cex = 0.72
)
grid()

p_correct_2afc <- 1 - pnorm(
  0, delta_difference, sd_difference
)
cat(sprintf("Probability correct in 2I-2AFC: %.4f\n", p_correct_2afc))
# Why 1/sqrt(2)? When A is in interval 1, mean(D)=+Delta; when it is
# in interval 2, mean(D)=-Delta, so the two D curves are 2*Delta apart.
# Independent observations add their variances: sigma^2+sigma^2=2*sigma^2,
# making SD(D)=sqrt(2)*sigma. Either mean is Delta from the zero boundary, so
# its standardized distance is Delta/(sqrt(2)*sigma)=d'/sqrt(2):
#   P(correct in 2I-2AFC) = Phi(d'/sqrt(2)).
# In plain language, this is the blue area right of zero in Figure 6 (and the
# symmetric red area left). The full distance between D curves is sqrt(2)*d';
# that is the same geometry viewed peak-to-peak instead of peak-to-boundary.
#
# Green and Swets's area theorem says, under the standard assumptions:
#   P(X_A > X_B) = P(correct in 2I-2AFC) = AUC.
# In plain language, this is the chance that a random A observation produces
# more evidence than a random B observation. Empirical AUC and Mann-Whitney U
# count the same A-B orderings (half credit for ties). U tests group difference;
# AUC describes discrimination. See Green & Swets (1966), Signal Detection
# Theory and Psychophysics, and Bamber (1975), doi:10.1016/0022-2496(75)90001-2.
# Order effects, unequal interval noise, or interval preference can add bias and
# break the area-theorem correspondence.
#
# Balanced yes/no accuracy at the midpoint criterion is Phi(d'/2). In plain
# language, Figure 1's line is half the peak separation from either peak, and
# accuracy is the bell-curve area on the correct side of that line.
stopifnot(
  abs(p_correct_2afc - auc_analytic) < 1e-12,
  abs(p_correct_2afc - roc_auc) < 5e-4
)

# -----------------------------------------------------------------------------
# Appendix A5. Unequal priors and error costs
# -----------------------------------------------------------------------------
# Say "signal" when the evidence is sufficiently more plausible under the
# signal curve. "Sufficiently" depends on base rates and mistake costs:
#   beta_optimal = P(noise)/P(signal) *
#                  (C_FA-C_CR)/(C_M-C_H).
# In plain language, the likelihood ratio is signal-curve height divided by
# noise-curve height at the observation. The first ratio on the right describes
# how common each source is; the second describes consequences of the outcomes.
# With equal costs and P(noise)=3/4, P(signal)=1/4, beta_optimal=3. Figure 7A
# scales each curve by its frequency; their crossing maximizes accuracy, as
# Figure 7B shows. It need not be the unweighted crossing or mean midpoint.

prior_noise <- 3 / 4
prior_signal <- 1 / 4
weighted_noise <- prior_noise * pdf_noise
weighted_signal <- prior_signal * pdf_signal
weighted_intersection <- find_curve_crossing(
  x, weighted_signal - weighted_noise, (loc_noise + loc_signal) / 2
)
p_correct_unequal <-
  prior_signal * tpr_theoretical + prior_noise * (1 - fpr_theoretical)
analytic_weighted_intersection <-
  (loc_noise + loc_signal) / 2 +
  sd_noise^2 * log(prior_noise / prior_signal) / (loc_signal - loc_noise)
stopifnot(
  abs(weighted_intersection - analytic_weighted_intersection) < 2 * diff(x)[1],
  abs(thresholds[which.max(p_correct_unequal)] - weighted_intersection) <
    2 * diff(thresholds)[1]
)

old_par <- par(mfrow = c(1, 2))
plot(
  x, weighted_noise, type = "l", col = "red", lwd = 2,
  xlab = "Internal response", ylab = "Prior-weighted density",
  main = "Figure 7A. Prior-weighted response densities"
)
lines(x, weighted_signal, col = "blue", lwd = 2)
points(
  weighted_intersection,
  prior_signal * dnorm(weighted_intersection, loc_signal, sd_signal),
  pch = 19
)
legend(
  "topright", c("Noise curve x its 3-in-4 chance", "Signal curve x its 1-in-4 chance"),
  col = c("red", "blue"), lty = 1, lwd = 2, bty = "n"
)
grid()

plot(
  thresholds, p_correct_unequal, type = "l", lwd = 2,
  xlab = "Threshold", ylab = "Chance of a correct response",
  main = "Figure 7B. Accuracy as the threshold moves"
)
abline(v = weighted_intersection, lty = 2)
grid()
par(old_par)

# -----------------------------------------------------------------------------
# Appendix A6. A non-Gaussian example
# -----------------------------------------------------------------------------
# Figure 8 replaces Figure 1's symmetric bell curves with skewed evidence
# distributions. The skew-normal shape parameter a controls the direction and
# degree of leaning. The density is 2*phi(z)*Phi(a*z)/scale. These small local
# functions avoid requiring the optional sn package.

skew_normal_pdf <- function(value, shape, location, scale) {
  z <- (value - location) / scale
  2 * dnorm(z) * pnorm(shape * z) / scale
}

skew_normal_cdf <- function(value, shape, location, scale) {
  vapply(
    value,
    function(upper) integrate(
      skew_normal_pdf, -Inf, upper,
      shape = shape, location = location, scale = scale,
      rel.tol = 1e-8
    )$value,
    numeric(1)
  )
}

rskew_normal <- function(n, shape, location, scale) {
  delta <- shape / sqrt(1 + shape^2)
  location + scale * (
    delta * abs(rnorm(n)) + sqrt(1 - delta^2) * rnorm(n)
  )
}

x_skew <- seq(0, 100, length.out = 1000)
shape_noise <- 2
loc_noise_skew <- 35
scale_noise_skew <- 10
shape_signal <- -2
loc_signal_skew <- 65
scale_signal_skew <- 10
pdf_noise_skew <- skew_normal_pdf(
  x_skew, shape_noise, loc_noise_skew, scale_noise_skew
)
pdf_signal_skew <- skew_normal_pdf(
  x_skew, shape_signal, loc_signal_skew, scale_signal_skew
)

plot(
  x_skew, pdf_noise_skew, type = "l", col = "red", lwd = 2,
  xlab = "Internal response", ylab = "Density",
  main = "Figure 8. A non-Gaussian pair of evidence distributions"
)
lines(x_skew, pdf_signal_skew, col = "blue", lwd = 2)
legend(
  "topright",
  c(
    sprintf("Noise: a=%g, loc=%g, scale=%g", shape_noise, loc_noise_skew, scale_noise_skew),
    sprintf("Signal: a=%g, loc=%g, scale=%g", shape_signal, loc_signal_skew, scale_signal_skew)
  ),
  col = c("red", "blue"), lty = 1, lwd = 2, bty = "n"
)
grid()

set.seed(603)
n_skew_samples <- 10000
simulated_noise_skew <- rskew_normal(
  n_skew_samples, shape_noise, loc_noise_skew, scale_noise_skew
)
simulated_signal_skew <- rskew_normal(
  n_skew_samples, shape_signal, loc_signal_skew, scale_signal_skew
)
p_correct_skew <- mean(simulated_signal_skew > simulated_noise_skew)

thresholds_skew <- seq(min(x_skew), max(x_skew), length.out = 100)
tpr_skew <- 1 - skew_normal_cdf(
  thresholds_skew, shape_signal, loc_signal_skew, scale_signal_skew
)
fpr_skew <- 1 - skew_normal_cdf(
  thresholds_skew, shape_noise, loc_noise_skew, scale_noise_skew
)
auc_skew <- auc_trapezoid(c(1, fpr_skew, 0), c(1, tpr_skew, 0))

cat(sprintf("Skew-normal simulated 2AFC probability correct: %.4f\n", p_correct_skew))
cat(sprintf("Skew-normal ROC AUC: %.4f\n", auc_skew))
stopifnot(
  auc_skew > 0 && auc_skew < 1,
  p_correct_skew > 0 && p_correct_skew < 1,
  abs(p_correct_skew - auc_skew) < 0.02
)

cat("All internal consistency checks passed.\n")
