# Signal detection theory: from an ideal observer to psychometric functions
# Copyright © 2026 Suresh Krishna.
# Licensed as a complete educational work under CC BY-NC-SA 4.0:
# https://creativecommons.org/licenses/by-nc-sa/4.0/
# Attribution details:
# https://github.com/m2b3/QuantBehavior/blob/main/LICENSE-CONTENT.md
#
# Standalone R companion to sdt.py. Run with:
#   Rscript sdt.R
# or source it from RStudio. It uses only base R (including the recommended
# stats and graphics packages), so no package installation is required.
#
# Contents
#   1. The ideal equal-variance model
#   2. What changes in real observers?
#   3. Simulated yes/no data
#   4. Fit a psychometric function
#   5. From SDT to stimulus-dependent psychometric functions
#   Appendix: selected extensions

options(stringsAsFactors = FALSE)

# Small helpers used throughout. Sorting inside auc_trapezoid makes it work
# whether an ROC was generated by increasing or decreasing thresholds.
auc_trapezoid <- function(x, y) {
  keep <- is.finite(x) & is.finite(y)
  x <- x[keep]
  y <- y[keep]
  ordering <- order(x)
  x <- x[ordering]
  y <- y[ordering]
  sum(diff(x) * (head(y, -1) + tail(y, -1)) / 2)
}

find_curve_crossing <- function(grid, difference, target = mean(range(grid))) {
  crossing_indices <- which(diff(sign(difference)) != 0)
  if (length(crossing_indices) == 0) {
    stop("No curve crossing was found on the supplied grid.")
  }
  crossings <- vapply(crossing_indices, function(index) {
    x1 <- grid[index]
    x2 <- grid[index + 1]
    y1 <- difference[index]
    y2 <- difference[index + 1]
    x1 - y1 * (x2 - x1) / (y2 - y1)
  }, numeric(1))
  crossings[which.min(abs(crossings - target))]
}

simulate_yes_count <- function(mean_response, n_trials, criterion, lapse) {
  internal_response <- rnorm(n_trials, mean_response, 1)
  respond_yes <- internal_response > criterion
  lapse_trials <- runif(n_trials) < lapse
  respond_yes[lapse_trials] <- runif(sum(lapse_trials)) < 0.5
  sum(respond_yes)
}

# -----------------------------------------------------------------------------
# 1. The ideal equal-variance model
# -----------------------------------------------------------------------------
# Imagine equally common signal and noise trials. Each trial creates a noisy,
# one-dimensional internal response. Signal responses tend to be larger, but
# the distributions overlap. Examples include baggage screening, radiology,
# hearing one's name, or diagnosing a sample from a noisy test.
#
# Our deliberately idealized starting assumptions are Gaussian signal and
# noise distributions with equal variance, independent stationary trials, one
# fixed decision criterion, and no stimulus-independent guesses or lapses.

x <- seq(0, 100, length.out = 1000)
diff_x <- seq(-100, 100, length.out = 1000)
loc_noise <- 40
sd_noise <- 10
loc_signal <- 60
sd_signal <- 10
pdf_noise <- dnorm(x, loc_noise, sd_noise)
pdf_signal <- dnorm(x, loc_signal, sd_signal)
intersection_point <- find_curve_crossing(
  x, pdf_signal - pdf_noise, (loc_noise + loc_signal) / 2
)

plot(
  x, pdf_noise, type = "l", col = "red", lwd = 2,
  xlab = "Internal response", ylab = "Density",
  main = "Response when signal is present or absent"
)
lines(x, pdf_signal, col = "blue", lwd = 2)
points(
  intersection_point,
  dnorm(intersection_point, loc_signal, sd_signal),
  pch = 19
)
legend(
  "topright",
  c(
    sprintf("Noise: mean=%g, SD=%g", loc_noise, sd_noise),
    sprintf("Signal: mean=%g, SD=%g", loc_signal, sd_signal)
  ),
  col = c("red", "blue"), lty = 1, lwd = 2, bty = "n"
)
grid()

# Respond "signal" when the response exceeds a threshold. Very low thresholds
# create many hits and false alarms; very high thresholds create few of both.
# In multidimensional or non-Gaussian problems, the optimal acceptance region
# can be more complicated than one threshold.
thresholds <- seq(min(x), max(x), length.out = 1000)
tpr_theoretical <- 1 - pnorm(thresholds, loc_signal, sd_signal)
fpr_theoretical <- 1 - pnorm(thresholds, loc_noise, sd_noise)
p_correct_theoretical <- 0.5 * (tpr_theoretical + 1 - fpr_theoretical)

roc_fpr_theoretical <- c(1, fpr_theoretical, 0)
roc_tpr_theoretical <- c(1, tpr_theoretical, 0)
roc_auc <- auc_trapezoid(roc_fpr_theoretical, roc_tpr_theoretical)
cat(sprintf("Area under the theoretical ROC curve: %.4f\n", roc_auc))

# Internal checks use analytic identities that do not depend on a random seed.
dprime_theoretical <- (loc_signal - loc_noise) / sd_noise
auc_analytic <- pnorm(dprime_theoretical / sqrt(2))
stopifnot(
  abs(sd_signal - sd_noise) < .Machine$double.eps^0.5,
  abs(intersection_point - (loc_noise + loc_signal) / 2) < 2 * diff(x)[1],
  abs(roc_auc - auc_analytic) < 5e-4,
  abs(max(p_correct_theoretical) - pnorm(dprime_theoretical / 2)) < 5e-4
)

set.seed(602)
n_trials <- 10000
n_half <- n_trials %/% 2
samples_noise <- rnorm(n_half, loc_noise, sd_noise)
samples_signal <- rnorm(n_half, loc_signal, sd_signal)
samples <- c(samples_noise, samples_signal)
labels <- c(rep(FALSE, n_half), rep(TRUE, n_half))

tpr_simulation <- numeric(length(thresholds))
fpr_simulation <- numeric(length(thresholds))
for (i in seq_along(thresholds)) {
  predictions <- samples > thresholds[i]
  tpr_simulation[i] <- mean(predictions[labels])
  fpr_simulation[i] <- mean(predictions[!labels])
}

old_par <- par(mfrow = c(1, 2))
plot(
  thresholds, p_correct_theoretical, type = "l", lwd = 2,
  xlab = "Threshold", ylab = "Probability correct",
  main = "Accuracy versus threshold"
)
abline(v = intersection_point, lty = 2)
grid()

plot(
  roc_fpr_theoretical, roc_tpr_theoretical, type = "l", lwd = 2,
  xlim = c(0, 1), ylim = c(0, 1),
  xlab = "False-positive rate = 1 - specificity",
  ylab = "True-positive rate = sensitivity",
  main = "Theoretical and simulated ROC"
)
lines(c(1, fpr_simulation, 0), c(1, tpr_simulation, 0), lty = 2, lwd = 2)
abline(0, 1, col = "navy", lty = 3)
legend(
  "bottomright", c("Theoretical", "Simulation", "Chance"),
  lty = c(1, 2, 3), lwd = 2, col = c("black", "black", "navy"), bty = "n"
)
grid()
par(old_par)

# Standard SDT measures
# For criterion k, H = P(X > k | signal) and F = P(X > k | noise).
# Under the equal-variance Gaussian model:
#   d'   = qnorm(H) - qnorm(F) = (mu_signal - mu_noise) / sigma
#   c    = -0.5 * (qnorm(H) + qnorm(F))
#   beta = f_signal(k) / f_noise(k) = exp(d' * c)
# c = 0 is unbiased, c > 0 conservative, and c < 0 liberal. With equal
# priors and equal error costs, the optimal criterion has c = 0 and beta = 1.
# The likelihood-ratio decision rule is more general than these formulas.

# -----------------------------------------------------------------------------
# 2. What changes in real observers?
# -----------------------------------------------------------------------------
# The ideal model is a baseline, not a literal description of every observer.
#
# Ideal assumption             Plausible departure / consequence
# Equal Gaussian variance      Unequal or non-Gaussian evidence changes ROC shape
# One fixed criterion          Drift, sequential bias, or payoff changes add variance
# Fixed sensitivity            Learning, fatigue, attention, and adaptation change d'
# No guesses or lapses         Stimulus-independent responses alter both asymptotes
# One mechanism                Strategy/state mixtures may not form one sigmoid
# Independent binomial trials  Serial dependence causes overdispersion
#
# Add complexity only when the design identifies it. Inspect residuals, recover
# parameters in simulations, compare constrained models, and prefer predictive
# or principled model comparisons over appearance alone. With unequal Gaussian
# variances, use a binormal/zROC analysis. AUC, A', and d_a answer related but
# different questions and do not rescue a poorly identified design.

# -----------------------------------------------------------------------------
# 3. Simulated yes/no data
# -----------------------------------------------------------------------------
# On signal trials, contrast x raises the mean internal response linearly:
#   X | signal,x ~ Normal(d'(x), 1), with d'(x) = gain * x.
# Noise-only catch trials have mean zero. The observer says "signal" when X > k.
# On a lapse trial the response is random.

set.seed(604)
contrast_levels <- c(0.25, 0.5, 1, 2, 4, 8, 12, 16)
n_per_level <- 160
n_catch <- 240
gain_true <- 0.25
criterion_true <- 1.0
lapse_true <- 0.02
true_dprime <- gain_true * contrast_levels

yes_counts <- vapply(
  true_dprime,
  simulate_yes_count,
  integer(1),
  n_trials = n_per_level,
  criterion = criterion_true,
  lapse = lapse_true
)
false_alarm_count <- simulate_yes_count(
  0, n_catch, criterion_true, lapse_true
)
false_alarm_rate <- false_alarm_count / n_catch

psychometric_data <- data.frame(
  contrast = contrast_levels,
  yes = yes_counts,
  trials = rep(n_per_level, length(contrast_levels))
)

contrast_grid <- seq(0, max(contrast_levels), length.out = 400)
p_yes_generating <- lapse_true / 2 +
  (1 - lapse_true) * pnorm(gain_true * contrast_grid - criterion_true)
plot(
  contrast_grid, p_yes_generating, type = "l", lwd = 2,
  xlab = "Contrast (%)", ylab = "Proportion 'signal' responses",
  ylim = c(0, 1), main = "Simulated yes/no data"
)
points(contrast_levels, yes_counts / n_per_level, pch = 19, col = "blue")
points(0, false_alarm_rate, pch = 4, cex = 1.4, lwd = 2, col = "red")
legend(
  "bottomright",
  c("Generating model", "Signal trials", "Noise-only catch trials"),
  col = c("black", "blue", "red"), lty = c(1, NA, NA),
  pch = c(NA, 19, 4), lwd = c(2, NA, 2), bty = "n"
)
grid()

cat(sprintf(
  "Catch trials: %d/%d; F = %.3f\n",
  false_alarm_count, n_catch, false_alarm_rate
))
cat("Contrast | signal responses / trials\n")
for (i in seq_along(contrast_levels)) {
  cat(sprintf("%8.2f | %3d / %d\n", contrast_levels[i], yes_counts[i], n_per_level))
}

# -----------------------------------------------------------------------------
# 4. Fit a psychometric function
# -----------------------------------------------------------------------------
# R has several possible psychometric-fitting routes. stats::glm is excellent
# for ordinary logit/probit binomial models without fitted lapses. The psyphy
# package (sometimes described informally as "R psychophysics") supplies SDT
# utilities, psychophysical GLM links, and psyfun.2asym; quickpsy adds a convenient
# multi-group/bootstrap workflow; brms can express richer Bayesian models. To
# keep this file immediately runnable, the code below directly maximizes the
# grouped-binomial likelihood with base stats::optim. This also lets us impose
# the same lower/upper-asymptote constraint used in the Python and MATLAB files.
#
# Curve choices:
#   norm     additive Gaussian decision noise: Phi(beta * (x - alpha))
#   logistic logistic decision noise: plogis(beta * (x - alpha))
#   weibull  positive intensities: 1 - exp(-(x / alpha)^beta)
#
# The response probability is q + (1 - 2q) * core(x), where the lower and
# upper error asymptotes are constrained to the same q. Under random lapses,
# the corresponding total lapse probability is 2q.

sigmoid_name <- "norm"  # Change to "logistic" or "weibull".

predict_psychometric <- function(theta, stimulus, sigmoid) {
  # q is constrained to (0, 0.1), slope/scale parameters stay positive.
  q <- 0.1 * plogis(theta[3])
  if (sigmoid == "weibull") {
    alpha <- exp(theta[1])
    beta <- exp(theta[2])
    core <- 1 - exp(-(pmax(stimulus, 0) / alpha)^beta)
  } else {
    alpha <- theta[1]
    beta <- exp(theta[2])
    linear_predictor <- beta * (stimulus - alpha)
    core <- if (sigmoid == "norm") pnorm(linear_predictor) else
      plogis(linear_predictor)
  }
  q + (1 - 2 * q) * core
}

psychometric_nll <- function(theta, data, sigmoid) {
  probabilities <- predict_psychometric(theta, data$contrast, sigmoid)
  probabilities <- pmin(pmax(probabilities, 1e-12), 1 - 1e-12)
  -sum(dbinom(data$yes, data$trials, probabilities, log = TRUE))
}

if (sigmoid_name == "weibull") {
  theta_start <- c(log(median(contrast_levels)), log(2), qlogis(0.1))
} else {
  theta_start <- c(median(contrast_levels), log(0.25), qlogis(0.1))
}

psychometric_fit <- optim(
  theta_start,
  psychometric_nll,
  data = psychometric_data,
  sigmoid = sigmoid_name,
  method = "Nelder-Mead",
  control = list(maxit = 10000, reltol = 1e-10),
  hessian = TRUE
)

fit_theta <- psychometric_fit$par
fit_q <- 0.1 * plogis(fit_theta[3])
if (sigmoid_name == "weibull") {
  fit_alpha <- exp(fit_theta[1])
  fit_beta <- exp(fit_theta[2])
} else {
  fit_alpha <- fit_theta[1]
  fit_beta <- exp(fit_theta[2])
}

fit_grid <- seq(0, max(contrast_levels), length.out = 400)
fit_probability <- predict_psychometric(fit_theta, fit_grid, sigmoid_name)
plot(
  fit_grid, fit_probability, type = "l", lwd = 2,
  xlab = "Contrast (%)", ylab = "P('signal' response | signal trial)",
  ylim = c(0, 1), main = sprintf("Binomial ML fit: %s", sigmoid_name)
)
points(contrast_levels, yes_counts / n_per_level, pch = 19, col = "blue")
grid()

cat(sprintf(
  paste0(
    "Psychometric fit (%s): alpha = %.4f, beta = %.4f, ",
    "equal asymptote q = %.4f (random-lapse probability = %.4f); convergence = %d\n"
  ),
  sigmoid_name, fit_alpha, fit_beta, fit_q, 2 * fit_q,
  psychometric_fit$convergence
))
stopifnot(
  psychometric_fit$convergence == 0,
  is.finite(psychometric_fit$value),
  all(fit_probability > 0 & fit_probability < 1),
  fit_beta > 0,
  fit_q >= 0 && fit_q <= 0.1
)

# -----------------------------------------------------------------------------
# 5. From SDT to stimulus-dependent psychometric functions
# -----------------------------------------------------------------------------
# With unit variance and fixed criterion k:
#   H(x) = Phi(d'(x) - k), and F = Phi(-k).
# Thus H(x) depends jointly on the decision rule and the transducer mapping the
# physical stimulus to sensitivity. If d'(x) = gain*x, H(x) is cumulative
# Gaussian in x. A common nonlinear extension is d'(x) = (gain*x)^p.
#
# Fit signal and noise responses jointly when asking whether a manipulation
# changes gain, exponent, criterion, or lapse rate. If false-alarm rate or
# criterion changes with stimulus or condition, fitting hit rates alone
# confounds sensitivity and bias.

# The log-linear correction avoids infinite z-scores for observed rates 0 or 1.
hit_rate_corrected <- (yes_counts + 0.5) / (n_per_level + 1)
false_alarm_rate_corrected <- (false_alarm_count + 0.5) / (n_catch + 1)
empirical_dprime <- qnorm(hit_rate_corrected) - qnorm(false_alarm_rate_corrected)
stopifnot(
  all(is.finite(empirical_dprime)),
  length(empirical_dprime) == length(contrast_levels)
)

plot(
  contrast_levels, empirical_dprime, pch = 19,
  xlab = "Contrast (%)", ylab = "d'",
  main = "Stimulus-dependent sensitivity"
)
lines(contrast_levels, true_dprime, lwd = 2)
legend(
  "topleft", c("Estimated from H and F", sprintf("Generating d' = %.2f x", gain_true)),
  pch = c(19, NA), lty = c(NA, 1), lwd = c(NA, 2), bty = "n"
)
grid()

# -----------------------------------------------------------------------------
# Appendix A1. Estimating SDT measures from response counts
# -----------------------------------------------------------------------------
#                Respond "signal"  Respond "noise"
# Actual signal       Hit               Miss
# Actual noise        False alarm       Correct rejection
#
# H conditions on signal trials; F conditions on noise trials. Precision,
# hits/(hits + false alarms), instead conditions on the response and therefore
# changes with the signal base rate.

hits <- 40
misses <- 10
false_alarms <- 15
correct_rejections <- 135
hit_rate <- hits / (hits + misses)
false_alarm_rate_example <- false_alarms / (false_alarms + correct_rejections)
precision <- hits / (hits + false_alarms)
hit_rate_corrected_example <- (hits + 0.5) / (hits + misses + 1)
fa_rate_corrected_example <-
  (false_alarms + 0.5) / (false_alarms + correct_rejections + 1)
z_hit <- qnorm(hit_rate_corrected_example)
z_false_alarm <- qnorm(fa_rate_corrected_example)
dprime_observed <- z_hit - z_false_alarm
criterion_observed <- -0.5 * (z_hit + z_false_alarm)
stopifnot(
  is.finite(dprime_observed),
  is.finite(criterion_observed),
  dprime_observed > 0
)

cat(sprintf(
  "Hit rate: %.3f; false-alarm rate: %.3f\n",
  hit_rate, false_alarm_rate_example
))
cat(sprintf(
  "Corrected d': %.3f; corrected c: %.3f; precision: %.3f\n",
  dprime_observed, criterion_observed, precision
))

# Appendix A2. Unequal variance and alternative sensitivity indices
# If sigma_signal != sigma_noise, qnorm(H)-qnorm(F) varies with criterion.
# The zROC follows:
#   qnorm(H) = (mu_signal-mu_noise)/sigma_signal
#              + (sigma_noise/sigma_signal) * qnorm(F).
# Its slope is sigma_noise/sigma_signal, not 1. The log likelihood ratio is
# quadratic, so an optimal decision region can require two crossings. ROC/AUC
# and the general likelihood-ratio rule remain valid. A', d_a, and equal-
# variance d' have different interpretations and should be labelled clearly.

# -----------------------------------------------------------------------------
# Appendix A3. Two-interval, two-alternative forced choice
# -----------------------------------------------------------------------------
# Each trial contains one signal and one noise sample; choose the larger. Under
# independent draws from the same decision variable there is no criterion/caution
# term, although order and response biases may remain.

pdf_signal_minus_noise <- dnorm(
  diff_x, loc_signal - loc_noise, sqrt(sd_noise^2 + sd_signal^2)
)
pdf_noise_minus_signal <- dnorm(
  diff_x, loc_noise - loc_signal, sqrt(sd_noise^2 + sd_signal^2)
)
plot(
  diff_x, pdf_signal_minus_noise, type = "l", col = "blue", lwd = 2,
  xlab = "Difference", ylab = "Density",
  main = "Difference distributions in 2I-2AFC"
)
lines(diff_x, pdf_noise_minus_signal, col = "red", lwd = 2)
legend(
  "topright", c("Signal - noise", "Noise - signal"),
  col = c("blue", "red"), lty = 1, lwd = 2, bty = "n"
)
grid()

p_correct_2afc <- 1 - pnorm(
  0, loc_signal - loc_noise, sqrt(sd_noise^2 + sd_signal^2)
)
cat(sprintf("Probability correct in 2I-2AFC: %.4f\n", p_correct_2afc))
# Under the standard assumptions, P(correct in 2AFC) = AUC = Phi(d'/sqrt(2)).
# Balanced yes/no accuracy at the optimal criterion is Phi(d'/2).
stopifnot(
  abs(p_correct_2afc - auc_analytic) < 1e-12,
  abs(p_correct_2afc - roc_auc) < 5e-4
)

# -----------------------------------------------------------------------------
# Appendix A4. Unequal priors and error costs
# -----------------------------------------------------------------------------
# Choose signal when the likelihood ratio exceeds
#   beta_optimal = P(noise)/P(signal) *
#                  (C_FA-C_CR)/(C_M-C_H).
# With equal error costs and P(noise)=3/4, P(signal)=1/4, beta_optimal=3.
# The accuracy-maximizing threshold is where prior-weighted densities cross.

prior_noise <- 3 / 4
prior_signal <- 1 / 4
weighted_noise <- prior_noise * pdf_noise
weighted_signal <- prior_signal * pdf_signal
weighted_intersection <- find_curve_crossing(
  x, weighted_signal - weighted_noise, (loc_noise + loc_signal) / 2
)
p_correct_unequal <-
  prior_signal * tpr_theoretical + prior_noise * (1 - fpr_theoretical)
analytic_weighted_intersection <-
  (loc_noise + loc_signal) / 2 +
  sd_noise^2 * log(prior_noise / prior_signal) / (loc_signal - loc_noise)
stopifnot(
  abs(weighted_intersection - analytic_weighted_intersection) < 2 * diff(x)[1],
  abs(thresholds[which.max(p_correct_unequal)] - weighted_intersection) <
    2 * diff(thresholds)[1]
)

old_par <- par(mfrow = c(1, 2))
plot(
  x, weighted_noise, type = "l", col = "red", lwd = 2,
  xlab = "Internal response", ylab = "Prior-weighted density",
  main = "Unequal priors"
)
lines(x, weighted_signal, col = "blue", lwd = 2)
points(
  weighted_intersection,
  prior_signal * dnorm(weighted_intersection, loc_signal, sd_signal),
  pch = 19
)
legend(
  "topright", c("P(noise) f_noise", "P(signal) f_signal"),
  col = c("red", "blue"), lty = 1, lwd = 2, bty = "n"
)
grid()

plot(
  thresholds, p_correct_unequal, type = "l", lwd = 2,
  xlab = "Threshold", ylab = "Probability correct",
  main = "Accuracy with P(noise) = 3/4"
)
abline(v = weighted_intersection, lty = 2)
grid()
par(old_par)

# -----------------------------------------------------------------------------
# Appendix A5. A non-Gaussian example
# -----------------------------------------------------------------------------
# The skew-normal density is 2*phi(z)*Phi(a*z)/scale. These small local
# functions avoid requiring the optional sn package.

skew_normal_pdf <- function(value, shape, location, scale) {
  z <- (value - location) / scale
  2 * dnorm(z) * pnorm(shape * z) / scale
}

skew_normal_cdf <- function(value, shape, location, scale) {
  vapply(
    value,
    function(upper) integrate(
      skew_normal_pdf, -Inf, upper,
      shape = shape, location = location, scale = scale,
      rel.tol = 1e-8
    )$value,
    numeric(1)
  )
}

rskew_normal <- function(n, shape, location, scale) {
  delta <- shape / sqrt(1 + shape^2)
  location + scale * (
    delta * abs(rnorm(n)) + sqrt(1 - delta^2) * rnorm(n)
  )
}

x_skew <- seq(0, 100, length.out = 1000)
shape_noise <- 2
loc_noise_skew <- 35
scale_noise_skew <- 10
shape_signal <- -2
loc_signal_skew <- 65
scale_signal_skew <- 10
pdf_noise_skew <- skew_normal_pdf(
  x_skew, shape_noise, loc_noise_skew, scale_noise_skew
)
pdf_signal_skew <- skew_normal_pdf(
  x_skew, shape_signal, loc_signal_skew, scale_signal_skew
)

plot(
  x_skew, pdf_noise_skew, type = "l", col = "red", lwd = 2,
  xlab = "Internal response", ylab = "Density",
  main = "Skew-normal response distributions"
)
lines(x_skew, pdf_signal_skew, col = "blue", lwd = 2)
legend(
  "topright",
  c(
    sprintf("Noise: a=%g, loc=%g, scale=%g", shape_noise, loc_noise_skew, scale_noise_skew),
    sprintf("Signal: a=%g, loc=%g, scale=%g", shape_signal, loc_signal_skew, scale_signal_skew)
  ),
  col = c("red", "blue"), lty = 1, lwd = 2, bty = "n"
)
grid()

set.seed(603)
n_skew_samples <- 10000
simulated_noise_skew <- rskew_normal(
  n_skew_samples, shape_noise, loc_noise_skew, scale_noise_skew
)
simulated_signal_skew <- rskew_normal(
  n_skew_samples, shape_signal, loc_signal_skew, scale_signal_skew
)
p_correct_skew <- mean(simulated_signal_skew > simulated_noise_skew)

thresholds_skew <- seq(min(x_skew), max(x_skew), length.out = 100)
tpr_skew <- 1 - skew_normal_cdf(
  thresholds_skew, shape_signal, loc_signal_skew, scale_signal_skew
)
fpr_skew <- 1 - skew_normal_cdf(
  thresholds_skew, shape_noise, loc_noise_skew, scale_noise_skew
)
auc_skew <- auc_trapezoid(c(1, fpr_skew, 0), c(1, tpr_skew, 0))

cat(sprintf("Skew-normal simulated 2AFC probability correct: %.4f\n", p_correct_skew))
cat(sprintf("Skew-normal ROC AUC: %.4f\n", auc_skew))
stopifnot(
  auc_skew > 0 && auc_skew < 1,
  p_correct_skew > 0 && p_correct_skew < 1,
  abs(p_correct_skew - auc_skew) < 0.02
)

cat("All internal consistency checks passed.\n")
